### ISSUE TITLE
Polygon with a hole not correct

### ISSUE THREAD

**Issue by christoph-buente** [jocelynj/osm-polygons-generation#1]
Hi,

i used your service on http://osm102.openstreetmap.fr/~jocelyn/polygons/index.py?id=62504 which is pretty great!

Unfortunately i was unable to import resulting WKT data into my postgis database. In this special case i think the generation of the polygon is not correct, as it is mainly an outline polygon with a hole. The resulting Multipolygon has more than one "holes". Maybe the OSM Data is corrupt. Could you have a look? This is how it should look like:

http://www.openstreetmap.org/browse/relation/62504

Thank you,

Christoph

**Comment by LukasKr** [comment]
@jocelynj http://polygons.openstreetmap.fr/ is down since yesterday. Any chance it will be up soon?

**Comment by jocelynj** [comment]
@LukasKr The server no longer boot correctly, so I don't know when it will be up. I'm still investigating how to restart the server.

**Comment by LukasKr** [comment]
@jocelynj i wish I could help out here but unfortunately my server skills are quite limited

**Comment by jocelynj** [comment]
@LukasKr I have re-installed the service on another server. It should now work correctly. (note that it would have been better to create a new issue instead of using this old issue to report this server failure)

**Comment by LukasKr** [comment]
thats great news. Regarding the issue: sure makes sense!
