### ISSUE TITLE
65995073 Doesn't work

### ISSUE THREAD

**Issue by mikey641** [jocelynj/osm-polygons-generation#4]
65995073 Doesn't work

**Comment by jocelynj** [comment]
Isn't it because the relations doesn't exists on osm.org ?

See http://www.openstreetmap.org/relation/65995073

**Comment by mikey641** [comment]
@jocelynj  [but it does exist](http://www.openstreetmap.org/way/65995073)

**Comment by jocelynj** [comment]
Ah ok.
http://polygons.openstreetmap.fr works only for relation, not for ways. If you want the geometry of a way, I'm not sure how you can get it - there might be another website that can give it.

**Comment by mikey641** [comment]
ok. thanks. 
btw, your tool is awesome.
